// constants/dummyData.ts

export const properties = [
  {
    id: 1,
    image: 'https://images.unsplash.com/photo-1572120360610-d971b9d7767c',
    title: 'Modern 2 Bedroom Apartment in New York',
    price: '1200',
    location: 'Downtown, New York',
    city: 'New York',
    type: 'rent',
    category: 'apartment',
    bedrooms: 2,
    bathrooms: 1,
    facilities: ['Parking', 'Kitchen', 'Free Wifi'],
    zip: 10001,
  },
  {
    id: 2,
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
    title: 'Luxury Condo with Skyline View',
    price: '2500',
    location: 'Manhattan, New York',
    city: 'New York',
    type: 'buy',
    category: 'house',
    bedrooms: 3,
    bathrooms: 2,
    facilities: ['Parking', 'Gym'],
    zip: 10002,
  },
  {
    id: 3,
    image: 'https://images.unsplash.com/photo-1600047506709-812f6f0ed87c',
    title: 'Beachside Villa in Miami',
    price: '3000',
    location: 'South Beach, Miami',
    city: 'Miami',
    type: 'rent',
    category: 'villa',
    bedrooms: 4,
    bathrooms: 3,
    facilities: ['Pool', 'Free Wifi', 'Garden'],
    zip: 33139,
  },
  {
    id: 4,
    image: 'https://images.unsplash.com/photo-1599423300746-b62533397364',
    title: 'Stylish Studio in Los Angeles',
    price: '1000',
    location: 'Hollywood, LA',
    city: 'Los Angeles',
    type: 'rent',
    category: 'apartment',
    bedrooms: 1,
    bathrooms: 1,
    facilities: ['Kitchen', 'Free Wifi'],
    zip: 90028,
  },
  {
    id: 5,
    image: 'https://images.unsplash.com/photo-1574169208507-843761648127',
    title: 'Suburban Family Home',
    price: '1800',
    location: 'Pasadena, California',
    city: 'Pasadena',
    type: 'buy',
    category: 'house',
    bedrooms: 3,
    bathrooms: 2,
    facilities: ['Parking', 'Garden'],
    zip: 91101,
  },
  {
    id: 6,
    image: 'https://images.unsplash.com/photo-1501183638710-841dd1904471',
    title: 'Quiet Land Parcel Near Woods',
    price: '800',
    location: 'Asheville, North Carolina',
    city: 'Asheville',
    type: 'buy',
    category: 'land',
    bedrooms: 0,
    bathrooms: 0,
    facilities: [],
    zip: 28801,
  },
  {
    id: 7,
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750',
    title: 'Luxury Hotel Suite with Ocean View',
    price: '4200',
    location: 'Waikiki Beach, Hawaii',
    city: 'Honolulu',
    type: 'rent',
    category: 'hotel',
    bedrooms: 2,
    bathrooms: 2,
    facilities: ['Pool', 'Free Wifi', 'Gym'],
    zip: 96815,
  },
  {
    id: 8,
    image: 'https://images.unsplash.com/photo-1519999482648-25049ddd37b1',
    title: 'Smart Home with Solar Roof',
    price: '3500',
    location: 'Austin, Texas',
    city: 'Austin',
    type: 'buy',
    category: 'house',
    bedrooms: 4,
    bathrooms: 3,
    facilities: ['Parking', 'Garden', 'Gym'],
    zip: 73301,
  },
  {
    id: 9,
    image: 'https://images.unsplash.com/photo-1599423300746-b62533397364',
    title: 'Downtown Loft with Exposed Brick',
    price: '2200',
    location: 'Chicago Loop, IL',
    city: 'Chicago',
    type: 'rent',
    category: 'apartment',
    bedrooms: 2,
    bathrooms: 2,
    facilities: ['Free Wifi', 'Kitchen'],
    zip: 60601,
  },
  {
    id: 10,
    image: 'https://images.unsplash.com/photo-1572120360610-d971b9d7767c',
    title: 'Minimalist Cabin Retreat',
    price: '1100',
    location: 'Flagstaff, Arizona',
    city: 'Flagstaff',
    type: 'rent',
    category: 'villa',
    bedrooms: 2,
    bathrooms: 1,
    facilities: ['Garden'],
    zip: 86001,
  },
];
